export const KAFKA_MODULE_SHARE_CONFIG = 'KAFKA_MODULE_SHARE_CONFIG';
export const KAFKA_MODULE_MESSAGE_QUEUE = 'KAFKA_MODULE_MESSAGE_QUEUE';
export const KAFKA_MODULE_SUBSCRIBE = 'KAFKA_MODULE_SUBSCRIBE';
export const BULL_MODULE_ON_QUEUE_EVENT = 'bull:module_on_queue_event';

export const KAFKA_MODULE_PROVIDER = 'KAFKA_MODULE_PROVIDER';
